spring.application.name=ecom-order-service
server.port = 8080
spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

logging.level.feign=DEBUG
logging.level.com.microservices.ecom_order_service.client=DEBUG

logging.level.org.springframework.cloud.client.discovery=DEBUG

